<?php
/**
 * Main constants.
 */

define( 'MAX_MARINE_INTERNATIONAL_SHIPPING_ENHANCEMENTS_PLUGIN_VERSION', '1.0.0' );

define( 'MAX_MARINE_INTERNATIONAL_SHIPPING_ENHANCEMENTS_PLUGIN_PATH', plugin_dir_path( __DIR__ ) );
define( 'MAX_MARINE_INTERNATIONAL_SHIPPING_ENHANCEMENTS_PLUGIN_BASENAME', plugin_basename( __DIR__ ) );
define( 'MAX_MARINE_INTERNATIONAL_SHIPPING_ENHANCEMENTS_PLUGIN_URL', trailingslashit( plugin_dir_url( __DIR__ ) ) );

define( 'MAX_MARINE_INTERNATIONAL_SHIPPING_ENHANCEMENTS_PLUGIN_OPTIONS_KEY', 'mmise_' );
